### ISSUE TITLE
確認一下 config 設定問題

### ISSUE THREAD

**Issue by Bright0505** [ablecool/Gatsby-test#1]
protocol
htaccess_user
htaccess_pass

這三個地方再看一下

**Comment by helomair** [comment]
已經更新了，但是還是無法連接，我發現在跑gatsby develop時有跳出error
![image](https://user-images.githubusercontent.com/26496854/97527092-75d48800-19e5-11eb-9126-0b8e8eaf4d4c.png)

目前有查到貌似是wordpress設定問題

**Comment by helomair** [comment]
會不會是我 ```restApiRoutePrefix``` 這個欄位的問題

**Comment by Bright0505** [comment]
確認一下 wordpress REST API 運作狀況

**Comment by helomair** [comment]
有了，改一下連結設定就行了
